version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: photomap-postgres
    environment:
      POSTGRES_DB: photomap
      POSTGRES_USER: photomap_user
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U photomap_user -d photomap"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
