name: "CI: Build, Test & SonarCloud Analysis"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest
    
    env:
      # Backend configuration
      DB_USERNAME: photomap_user
      DB_PASSWORD: test_password
      DB_NAME: photomap
      JWT_SECRET: test-secret-key-for-ci-only-not-for-production
      JWT_EXPIRATION: 86400000
      SECURITY_ENABLED: false
      
    steps:
      # ============================================
      # CHECKOUT & SETUP
      # ============================================
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones disabled for SonarCloud analysis
          
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          
      # ============================================
      # CACHING
      # ============================================
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar-
          
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
          
      # ============================================
      # BACKEND: BUILD & TEST
      # ============================================
      - name: Backend - Maven clean install
        working-directory: backend
        run: mvn clean install -DskipTests
        
      - name: Backend - Run tests with coverage
        working-directory: backend
        run: mvn test jacoco:report
        
      # ============================================
      # FRONTEND: BUILD & TEST
      # ============================================
      - name: Frontend - Install dependencies
        working-directory: frontend
        run: npm ci
        
      - name: Frontend - Run tests with coverage
        working-directory: frontend
        run: npm run test:coverage
        
      # ============================================
      # SONARCLOUD ANALYSIS
      # ============================================
      - name: Backend - SonarCloud analysis
        working-directory: backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}
        
      - name: Frontend - SonarCloud analysis
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      # ============================================
      # ARTIFACTS UPLOAD (Optional)
      # ============================================
      - name: Upload backend test reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: backend-test-reports
          path: backend/target/surefire-reports/
          retention-days: 7
          
      - name: Upload backend coverage reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: backend-coverage-reports
          path: backend/target/site/jacoco/
          retention-days: 7
          
      - name: Upload frontend coverage reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: frontend-coverage-reports
          path: frontend/coverage/
          retention-days: 7

  # ============================================
  # E2E TESTS WITH PLAYWRIGHT
  # ============================================
  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    needs: build
    if: false  # Temporarily disabled - debugging timeout issues

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: photomap_test
          POSTGRES_USER: photomap_test
          POSTGRES_PASSWORD: test123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    env:
      DB_HOST: localhost
      DB_PORT: 5433
      DB_NAME: photomap_test
      DB_USERNAME: photomap_test
      DB_PASSWORD: test123
      JWT_SECRET: e2e-test-secret-key-minimum-32-characters
      SECURITY_ENABLED: true
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: admin123
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Backend - Build (skip tests)
        working-directory: backend
        run: mvn clean install -DskipTests

      - name: Backend - Apply Flyway migrations
        working-directory: backend
        run: |
          mvn flyway:migrate \
            -Dflyway.url=jdbc:postgresql://localhost:5433/photomap_test \
            -Dflyway.user=photomap_test \
            -Dflyway.password=test123

      - name: Frontend - Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps chromium

      - name: Install wait-on for health checks
        run: npm install -g wait-on

      - name: Start Backend in background
        working-directory: backend
        run: |
          nohup mvn spring-boot:run \
            -Dspring-boot.run.profiles=e2e \
            > backend.log 2>&1 &
          echo $! > backend.pid
          echo "Backend PID: $(cat backend.pid)"

      - name: Wait for Backend to be ready
        run: |
          echo "Waiting for Backend health check..."
          wait-on -t 60000 http://localhost:8080/actuator/health
          echo "Backend is ready!"

      - name: Start Frontend in background
        working-directory: frontend
        run: |
          nohup npm start > frontend.log 2>&1 &
          echo $! > frontend.pid
          echo "Frontend PID: $(cat frontend.pid)"

      - name: Wait for Frontend to be ready
        working-directory: frontend
        run: |
          echo "Waiting for Frontend..."
          wait-on -t 60000 http://localhost:4200
          echo "Frontend is ready!"

      - name: Run E2E tests
        working-directory: frontend
        run: npm run test:e2e

      - name: Stop Backend and Frontend
        if: always()
        run: |
          if [ -f backend/backend.pid ]; then
            echo "Stopping Backend (PID: $(cat backend/backend.pid))..."
            kill $(cat backend/backend.pid) || true
          fi
          if [ -f frontend/frontend.pid ]; then
            echo "Stopping Frontend (PID: $(cat frontend/frontend.pid))..."
            kill $(cat frontend/frontend.pid) || true
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-test-results
          path: frontend/test-results/
          retention-days: 7

      - name: Upload Backend logs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: backend-e2e-logs
          path: backend/backend.log
          retention-days: 7

      - name: Upload Frontend logs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: frontend-e2e-logs
          path: frontend/frontend.log
          retention-days: 7
